### PR TITLE
removed hack-pack

### PR DESCRIPTION
**Pull request by tejasag**
Removed the Hack Pack page because it no longer exists.

(PS. the formatting was done by `yarn fmt` lol)

### CODE REVIEW

**Comment by lachlanjc** [comment]
#### 📝 Changed routes:


| [**/**](https://make-dino-eirrtjt3o.hackclub.dev/) | [**/slackAuthSuccess**](https://make-dino-eirrtjt3o.hackclub.dev/slackAuthSuccess) |
|:-:|:-:|
|<a href="https://make-dino-eirrtjt3o.hackclub.dev/">Screenshot of /</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/aRWn152elg4KD1bOMNnxBhuTfdVkOhQU9Adr-RMBt1XSBL2Qrht1_0w_T7hooO_1fG0Lx722-ct7PIGCRo8gzQ.png">(view full size)</a> |<a href="https://make-dino-eirrtjt3o.hackclub.dev/slackAuthSuccess">Screenshot of /slackAuthSuccess</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/FItMaOro725BgID38xwYsUX6H_O68_Xzrl0xClo7-2ONDJ5rNAups48Vj0o3tJNbhf4dDcQSvhA1iEF61qzerA.png">(view full size)</a> |







Commit d8fb3316e40b7b3a9b9f03d2606d564e6e23dad6 (https://make-dino-eirrtjt3o.hackclub.dev).

**Comment by tejasag** [comment]
~will be very pog if someone can add the hacktoberfest topic and tag. kthnxbai~

**Comment by sampoder** [comment]
could you undo the formatting please?

**Comment by tejasag** [comment]
sure lemme try

**Pull request closed without merging**
